version: "2"

services:

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.1
    container_name: kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  tweets_extract:
    build:
      dockerfile: docker/Dockerfile
      context: .
    container_name: tweets_extract
    environment:
      - KAFKA_SERVER=kafka:9092
      - KAFKA_TOPIC=tweets-raw
      - REMOVE_RETWEETS=True
      - MAX_RESULTS=10
      - TWEET_LANG=pt
      - SLEEP_TIME=60
    env_file:
      - .env
    command: python scripts/tweets_extract.py
    depends_on:
      - kafka
      - mongo
    restart: 'always'

  spark:
    image: bitnami/spark:3.1.2
    container_name: spark
    environment:
      - SPARK_MODE=master
      - KAFKA_SERVER=kafka:9092
      - KAFKA_RAW_TOPIC=tweets-raw
      - KAFKA_FINAL_TOPIC=tweets-final
    depends_on:
      - kafka
    restart: 'always'
    user: root
    volumes:
      - ./scripts:/scripts
    command: sh /scripts/spark_submit_tweets_transform.sh

  tweets_load:
    build:
      dockerfile: docker/Dockerfile
      context: .
    container_name: tweets_load
    environment:
      - KAFKA_SERVER=kafka:9092
      - KAFKA_TOPIC=tweets-final
      - MONGO_SERVER=mongo:27017
      - MONGO_DATABASE=tweets
      - MONGO_COLLECTION=tweets
    command: python scripts/tweets_load.py
    depends_on:
      - kafka
      - mongo
    restart: 'always'

  mongo:
    image: mongo:5.0.6
    container_name: mongo
    ports:
      - "27017:27017"
