teams_synonyms_mapping = {
    'fortaleza': 'fortaleza',
    'ceará': 'ceara',
    'américa mg': "america_mg",
    'américamg': "america_mg",
    'américa mineiro': "america_mg",
    'athletico': "athletico",
    'atlético go': "atletico_go",
    'atléticogo': "atletico_go",
    'atlético goianiense': "atletico_go",
    'atlético mg': "atletico_mg",
    'atléticomg': "atletico_mg",
    'atlético mineiro': "atletico_mg",
    'avai': "avai",
    'botafogo': "botafogo",
    'bragantino': "bragantino",
    'corinthians': "corinthians",
    'coritiba': "coritiba",
    'cuiaba': "cuiaba",
    'flamengo': "flamengo",
    'fluminense': "fluminense",
    'goias': "goias",
    'internacional': "internacional",
    'juventude': "juventude",
    'palmeiras': "palmeiras",
    'santos': "santos",
    'são paulo': "sao_paulo"
}

contexts = [
    'futebol',
    'escalação',
    'placar',
    'partida',
    'confronto',
    'enfrenta',
    'jogador',
    'jogo',
    'jogar',
    'time',
    'equipe',
    'seleção',
    'contrato',
    'contratação',
    'plantel',
    'ganhar',
    'ganhou',
    'vence',
    'venceu',
    'ganha',
    'ganhou',
    'bola',
    'chuteira',
    'estádio',
    'ingresso',
    'gramado',
    'trave',
    'travessão',
    'chute',
    'defesa',
    'ataque',
    'atacante',
    'zagueiro',
    'zaga',
    'lateral',
    'falta',
    'expulsão',
    'cartão',
    'perde',
    'perdeu',
    'rebaixamento',
    'vitória',
    'derrota',
    'brasileirão',
    'campeonato',
    'copa',
    'lance',
    'gol',
    'rodada',
    'enfrenta',
    'campeão',
    'rival',
    'rivais',
    'título',
    'campeões',
    'uniforme',
    'camisa',
    'libertadores',
    'transmissão',
    'assistir',
    'patrocinador',
    'patrocínio',
    'torcida',
    'torcedor',
    'arquibancada',
    'esporte',
    'juiz',
    'var',
    'arbitragem',
    'série a'
]