teams = [
    'fortaleza',
    'ceara',
    '"america mg"',
    '"america mineiro"',
    'athletico',
    '"atletico go"',
    '"atletico goianiense"',
    '"atletico mg"',
    '"atletico mineiro"',
    'avai',
    'botafogo',
    'bragantino',
    'corinthians',
    'coritiba',
    'cuiaba',
    'flamengo',
    'fluminense',
    'goias',
    'internacional',
    'juventude',
    'palmeiras',
    'santos',
    '"sao paulo"'
]